# Generated by Django 4.2.4 on 2023-08-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_about_me_education_image_projects_skills_delete_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
