# Generated by Django 4.2.4 on 2023-08-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_image_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_me',
            options={'verbose_name': 'About_me', 'verbose_name_plural': 'About_mes'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Projects', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skills', 'verbose_name_plural': 'Skills'},
        ),
    ]
